services:
  backend:
    image: docker.yapyap.pl/online-gaming-backend:${TAG}
    container_name: og-backend
    restart: always
    environment:
      - SERVER_PORT=8080

  frontend:
    image: docker.yapyap.pl/online-gaming-frontend:${TAG}
    container_name: og-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend