services:

  authorization:
    image: docker.yapyap.pl/online-gaming-authorization:${TAG}
    container_name: og-authorization
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gaming-net
    logging: &production-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  menu:
    image: docker.yapyap.pl/online-gaming-menu:${TAG}
    container_name: og-menu
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gaming-net
    logging: *production-logging

  social:
    image: docker.yapyap.pl/online-gaming-social:${TAG}
    container_name: og-social
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gaming-net
    logging: *production-logging

  makao:
    image: docker.yapyap.pl/online-gaming-makao:${TAG}
    container_name: og-makao
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gaming-net
    logging: *production-logging

  ludo:
    image: docker.yapyap.pl/online-gaming-ludo:${TAG}
    container_name: og-ludo
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gaming-net
    logging: *production-logging

  frontend:
    image: docker.yapyap.pl/online-gaming-frontend:${TAG}
    container_name: og-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - gaming-net
    logging: *production-logging
    depends_on:
      - authorization
      - menu
      - social
      - makao
      - ludo

networks:
  gaming-net:
    driver: bridge