version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: shared-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: og-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redispassword

  authorization:
    build:
      context: ./backend
      target: dev
      args:
        MODULE_NAME: authorization
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ./backend:/app
    depends_on:
       - mongo
       - redis

  menu:
    build:
      context: ./backend
      target: dev
      args:
        MODULE_NAME: menu
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - redis

  social:
    build:
      context: ./backend
      target: dev
      args:
        MODULE_NAME: social
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - redis

  makao:
    build:
      context: ./backend
      target: dev
      args:
        MODULE_NAME: makao
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - redis

  ludo:
    build:
      context: ./backend
      target: dev
      args:
        MODULE_NAME: ludo
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - authorization

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - authorization
      - menu
      - social
      - makao
      - ludo

volumes:
  mongo_data:
  redis_data: